---

services:

  app:
    build:
      context: .
    container_name: rus-dev-${USER}
    restart: unless-stopped
    # ports:
    # - "${HOST_IP:-127.0.0.1}:${HOST_PORT:-4001}:4001"
    ports:
      - "${HOST_IP:-127.0.0.1}:${HOST_PORT:-4001}:4001"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      RUST_LOG: info
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - cargo_target:/app/target
      - rus-data:/data

volumes:
  cargo_target:
    name: rus-cargo-target-${USER}
  rus-data:
    name: rus-data-${USER}
