---
# Build OCI image and push to Forgejo Container Registry.
#
# Tagging strategy:
#   - Push to main        → latest
#   - Push tag v1.2.3     → v1.2.3, latest
name: Build OCI container

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and push image
    runs-on: opensuse-base-16.0-v1
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ""
      REGISTRY_PROVIDER: dev.a8n.run
      REGISTRY_USER: ""
      REGISTRY_PASSWORD: ${{ secrets.FORGEJO_PAT }}
      DOCKER_BUILDKIT: 1

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: nu {0}
        run: |
          let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
          $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
          $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV

      - name: Determine image tags
        shell: nu {0}
        run: |
          let registry = $env.IMAGE_REGISTRY
          let ref = "${{ github.ref }}"
          let ref_name = "${{ github.ref_name }}"

          # Always tag as latest
          mut tags = [$"($registry)/rus:latest"]

          # Add version tag for git tag pushes
          if ($ref | str starts-with "refs/tags/v") {
              $tags = ($tags | append $"($registry)/rus:($ref_name)")
          }

          let tags_str = ($tags | str join "\n")
          print $"Image tags:\n($tags_str)"
          $"IMAGE_TAGS=($tags_str)\n" | save --append $env.GITHUB_ENV

      - name: Build image
        shell: nu {0}
        run: |
          let tags = ($env.IMAGE_TAGS | lines | where { $in | is-not-empty })
          let tag_args = ($tags | each { ["-t" $in] } | flatten)
          print $"Building with tags: ($tags)"
          ^docker build --build-arg BUILD_MODE=standalone ...$tag_args .

      - name: Push image to Forgejo Container Registry
        shell: nu {0}
        run: |
          ^docker login --username $env.REGISTRY_USER --password $env.REGISTRY_PASSWORD $env.REGISTRY_PROVIDER
          let tags = ($env.IMAGE_TAGS | lines | where { $in | is-not-empty })
          for tag in $tags {
              print $"Pushing: ($tag)"
              ^docker push $tag
          }

      - name: Print image URLs
        shell: nu {0}
        run: |
          let tags = ($env.IMAGE_TAGS | lines | where { $in | is-not-empty })
          print $"Images pushed:\n($tags | str join "\n")"
