---
# Build OCI image and push to Forgejo Container Registry.
name: Build OCI container

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and push image
    runs-on: opensuse-base-16.0-v1
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ""
      REGISTRY_PROVIDER: dev.a8n.run
      REGISTRY_USER: ""
      REGISTRY_PASSWORD: ${{ secrets.FORGEJO_PAT }}
      DOCKER_BUILDKIT: 1

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: nu {0}
        run: |
          let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
          $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
          $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV

      - name: Build image
        shell: nu {0}
        env:
          BUILD_VERSION: ${{ github.ref_name }}
        run: |
          let tag = ($env.BUILD_VERSION | str trim)
          let registry = $env.IMAGE_REGISTRY
          let image_name = $"($registry)/rus:($tag)"
          print $"Building image: ($image_name)"
          ^docker build --build-arg BUILD_MODE=standalone -t $image_name .
          $"IMAGE_NAME=($image_name)\n" | save --append $env.GITHUB_ENV

      - name: Push image to Forgejo Container Registry
        shell: nu {0}
        run: |
          ^docker login --username $env.REGISTRY_USER --password $env.REGISTRY_PASSWORD $env.REGISTRY_PROVIDER
          print $"Pushing image: ($env.IMAGE_NAME)"
          ^docker push $env.IMAGE_NAME

      - name: Print image URL
        shell: nu {0}
        run: |
          print $"Image pushed to ($env.IMAGE_NAME)"
