services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rus-app-${USER}
    # No need for ports since Traefik will handle the routing
    # ports:
      # - "${HOST_IP:-127.0.0.1}:${HOST_PORT:-4001}:4001"
    volumes:
      - rus-data:/data
    environment:
      - HOST=0.0.0.0
      - RUST_LOG=info
    env_file: .env
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.child-rus.rule: Host(`rus.a8n.run`)
      traefik.http.routers.child-rus.service: child-rus@docker
      traefik.http.routers.child-rus.entrypoints: web-secure
      traefik.http.routers.child-rus.tls.certresolver: cert-cloudflare
      traefik.http.services.child-rus.loadbalancer.server.port: 4001
    networks:
      - network-traefik-public

networks:
  network-traefik-public:
    external: true

volumes:
  rus-data:
    name: rus-data-${USER}
